# Generated by Django 5.2 on 2025-04-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=15)),
                ('expense_details', models.JSONField(default=dict)),
                ('date', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/%d/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
