# Generated by Django 5.2 on 2025-04-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
