# Generated by Django 5.2 on 2025-04-13 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('status', models.CharField(default='draft', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.customuser')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'week_start'], name='report_user_week_idx'), models.Index(fields=['status'], name='report_status_idx')],
            },
        ),
    ]
